---
- hosts: aws_ec2
  become: yes
  roles:
    - app

# run the playbook: ansible-playbook -i inventories/development/aws_ec2.yml playbooks/deploy.yml --extra-vars "ansible_ssh_private_key_file=/home/john/portfolio_John_Duran/app/terraform/key_saa"