Resources:

  # Security Group for Web (Apache on port 80)
  SgWeb:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref SecurityGroupName
      GroupDescription: Allow HTTP
      VpcId: vpc-53cd6b2e
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:                     # Add this section for outbound rules
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Terraform
          Value: yes
        - Key: aws_saa
          Value: yes

  # Instance for Apache (using Ubuntu or Amazon Linux)
  ApacheInstance:
    Type: AWS::EC2::Instance
    Condition: CreateProdResources
    Properties:
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref SgWeb
      ImageId: ami-0887e1d5e322290cf  # Ensure this AMI ID is valid in your region
      UserData: !Base64 |
        #!/bin/bash
        apt-get update
        apt-get install -y apache2
        echo "Hello World" > /var/www/html/index.html
        systemctl restart apache2
      Tags:
        - Key: Name
          Value: !Ref InstanceName
        - Key: Terraform                  # Consider standardizing tag keys
          Value: yes
        - Key: Updated
          Value: no
        - Key: Description
          Value: !FindInMap [Descriptions,!Ref "AWS::Region", desc1]
        - Key: Description_test_2
          Value: !FindInMap [Descriptions,Description2, descx]



Mappings:
  Descriptions:
    us-east-1: 
      desc1: Description Virginia 1
      desc2: Description Virginia 2
    Description2: 
      descx: Description 2

Parameters:
  SecurityGroupName:
    Description: Choose a name for the security group
    Type: String
    AllowedValues:
      - sg_apache
      - sg_web
    Default: sg_web
  
  InstanceName:
    Description: just another paramter for the instance name
    Type: String
    Default: aws_dvac02_apache_CF

Outputs:
  SgName:
    Description: The SgWeb name
    Value: !Ref SgWeb
    Export:
      Name: sgnameexported  #The exported value is to be used in another stack to create implicit dependencies
  
Conditions:
  CreateProdResources: !Equals [ sg_web,sg_web] # just testing conditions

