AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation template to create an S3 bucket with website hosting and public access settings"

Parameters:
  BucketName:
    Type: String
    Default: "demo-john-general-v1"
    Description: "The name of the S3 bucket"

Resources:
  # S3 Bucket
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  # Public Access Block Configuration
  S3BucketPublicAccessBlock:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Deny
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"

  # Bucket ACL
  S3BucketACL:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "BucketPolicy"
            Effect: "Allow"
            Principal: "*"
            Action:
              - "s3:ListBucket"
              - "s3:GetObject"
            Resource:
              - !Sub "arn:aws:s3:::${S3Bucket}/*"
