---
# roles/nginx/tasks/main.yml
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes  # this enables privileges

# shutdown the apache so that nginx can use the 80 port
- name: Shut down Apache2 service
  service:
    name: apache2
    state: stopped
    enabled: no
  become: yes  # this enables privileges


# my hosts  have a probelm with systemctl so they cannot start or status it. This is better to test it with my local virutalbox host changed in the playbook main
- name: Start and enable Nginx service
  service:
    name: nginx
    state: started
    enabled: yes
  notify:  # I define here the handler
    - Restart Nginx
  become: yes  # this enables privileges

- name: Install CURL
  apt:
    name: curl
    state: present
    update_cache: yes
  become: yes  # this enables privileges