stages:
  - deploy
  - validate_version
  - load_env_variables
  - validate_existing_infra_tags
  - validate_terraform_config

variables:
  TF_VERSION: "1.9.5"

image: amazon/aws-cli:latest #amazon/aws-cli # I'm not using an image just yet
cache:
  key: "${TF_VERSION}"
  paths:
    - "${TF_CACHE_DIR}"

before_script:
  - yum update -y
  - yum install -y unzip curl
  - mkdir -p $TF_CACHE_DIR
  - if [ ! -f "${TF_CACHE_DIR}/terraform" ]; then
      curl -fsSL -o terraform.zip https://releases.hashicorp.com/terraform/$TF_VERSION/terraform_${TF_VERSION}_linux_amd64.zip &&
      unzip terraform.zip &&
      mv terraform $TF_CACHE_DIR/terraform &&
      rm -f terraform.zip;
    fi
  - ln -sf $TF_CACHE_DIR/terraform /usr/local/bin/terraform
  - terraform version
  # - > # Installing AWS CLI
  #   - apt-get update && apt-get install -y jq
  #   curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip";
  #   unzip awscliv2.zip;
  #   ./aws/install;
  #   rm -rf awscliv2.zip aws;
#   - > # Installing Terraform
#     curl -fsSL "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip" -o terraform.zip;
#     unzip terraform.zip;
#     mv terraform /usr/local/bin/;
#     rm terraform.zip;
#   - apt-get update && apt-get install -y jq

  # - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
  # - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
  #- aws configure set region ${AWS_DEFAULT_REGION}
  # - export PATH=$PATH:/usr/local/bin
  # - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  # - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  # - export TF_API_TOKEN=${TF_API_TOKEN}

deploy:
  stage: deploy
  #image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws --version
    - aws s3api list-buckets --region us-east-1 --query "Buckets[].Name"
    - terraform -version

validate_version:
  stage: validate_version
  script:
    - aws --version
    - aws s3api list-buckets --region us-east-1 --query "Buckets[].Name"
    - env
    - 'echo "Current branch: ${CI_COMMIT_REF_NAME}"'
    - echo "Available tags:" && git tag
    - 'export VERSION=$(cat app/infra_version.txt)'
    - 'echo "VERSION=${VERSION}"'
    - 'TAG="${CI_COMMIT_REF_NAME}-infra-v${VERSION}"'
    - 'echo ${TAG}'
    - 'git fetch --tags'
    - 'git tag'
    - > 
      if ! git fetch --tags || ! git tag | grep -q "^${TAG}$"; then 
        echo "Error: No matching tag ${TAG} found." && exit 1;  
      fi
    - 'echo "TAG=${TAG}" >> variables.env'
    - 'echo "VERSION=${VERSION}" >> variables.env'
    - 'echo "ENVIRONMENT=${CI_COMMIT_REF_NAME}" >> variables.env'
  artifacts:
    reports:
      dotenv: variables.env 

load_env_variables:
  stage: load_env_variables
  needs: [validate_version]
  script:
    - env
    - 'echo TAG on second stage: ${TAG}'
    - 'ENVIRONMENT_UPPERCASE=$(echo "${ENVIRONMENT}" | tr "[:lower:]" "[:upper:]")'
    - 'grep "^${ENVIRONMENT_UPPERCASE}_" app/.env | sed -E "s/^${ENVIRONMENT_UPPERCASE}_//" >> variables.env'
    - 'echo "ENVIRONMENT_UPPERCASE: ${ENVIRONMENT_UPPERCASE}"'
    - 'echo "ENVIRONMENT: ${ENVIRONMENT}"'
    - 'echo "TAG: ${TAG}"'
    - env
    - 'echo "aws_region: ${aws_region}"'
    - 'echo "TAG=${TAG}" >> variables.env'
    - 'echo "VERSION=${VERSION}" >> variables.env'
    - 'echo "ENVIRONMENT=${CI_COMMIT_REF_NAME}" >> variables.env'
  artifacts:
    reports:
      dotenv: variables.env 

validate_existing_infra_tags:
  stage: validate_existing_infra_tags
  needs: [load_env_variables]
  script:
    - env
    - 'echo TAG on second stage: ${TAG}'
    - 'echo "AWS Region: ${aws_region}"'
    - |
      infra_version=$(aws ssm get-parameter --region "${aws_region}" \
        --name "/app/${ENVIRONMENT}/infrastructure_version" \
        --query "Parameter.Value" --output text 2>&1 || echo "ParameterNotFound")
      
      if [[ "${infra_version}" == "ParameterNotFound" ]]; then
        echo "No Infrastructure version found. Deploying tag: ${TAG}"
        echo "version_exists=false" >> variables.env
      elif [[ "${infra_version}" == "${TAG}" ]]; then
        echo "Infrastructure already at version ${TAG}. Skipping deployment."
        echo "version_exists=true" >> variables.env
      else
        echo "Different version detected (${infra_version}). Deploying new tag: ${TAG}"
        echo "version_exists=false" >> variables.env
      fi

validate_terraform_config:
  stage: validate_terraform_config
  needs: [validate_existing_infra_tags]
  script:

    - 'git checkout "${TAG}"'
    - terraform init
    - terraform fmt -check
    - terraform validate
  rules:
    - if: $version_exists == "false"  