stages:
  - validate_version

variables:
  TF_VERSION: "1.9.5"

before_script:
  - apt-get update && apt-get install -y jq

validate_version:
  stage: validate_version
  script:
    - env
    - 'echo "Current branch: ${CI_COMMIT_REF_NAME}"'
    - echo "Available tags:" && git tag
    - 'export VERSION=$(cat app/infra_version.txt)'
    - 'echo "VERSION=${VERSION}"'
    - 'TAG="${CI_COMMIT_REF_NAME}-infra-v${VERSION}"'
    #- 'if ! git fetch --tags || ! git tag | grep -q "^${TAG}$"; then echo "Error: No matching tag '${TAG}' found." && exit 1; fi'