stages:
  - validate_version

variables:
  TF_VERSION: "1.9.5"

before_script:
  - apt-get update && apt-get install -y jq

validate_version:
  stage: validate_version
  script:
    - echo "Current branch"
