stages:
  - set_variable
  - use_variable

set_variable_job:
  stage: set_variable
  script:
    - VALUE=false # Or the result of your command
    - 'echo "EXPORT UPDATED=${VALUE}" > variable.env'
    - env
  artifacts:
    paths:
      - variable.env

use_variable_job:
  stage: use_variable
  needs:
    - set_variable_job
  before_script:
    - source variable.env  # Load persisted variable

  script:
    - envs
    - 'echo "Updated variable is: ${UPDATED}"' # Verify
#  rules:
#    - if: '$UPDATED == "true"' # Check the variable AFTER sourcing it
#      when: always # Crucial: Always evaluate this rule
