workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'  # Exclude master branch
      #changes:
      #  - app/infra_version.txt  # Trigger only if this file changes
      when: always
    - when: never  # Prevents the pipeline from running otherwise

stages:
  - set_variable_job
  - use_variable_job
set_variable_job:
  stage: set_variable
  script:
    - VALUE=$(some_command_that_generates_value) # Run your command and capture the output
    - echo "EXPORT UPDATED=$VALUE" > variable.env # Export the variable to a .env file
  artifacts:
    paths:
      - variable.env

use_variable_job:
  stage: use_variable
  needs:
    - set_variable_job
  script:
    - source variable.env # Source the .env file
    - echo "Updated variable is: $UPDATED"
  rules:
    - if: '$UPDATED == "true"' # Or whatever condition you need