stages:
  - set_variable
  - use_variable
  - final_stage

set_variable_job:
  stage: set_variable
  script:
    - VALUE=false # Or the result of your command
    - 'echo "EXPORT UPDATED=${VALUE}" > variable.env'
    - env
    - 'exit 1'
  artifacts:
    paths:
      - variable.env
  allow_failure: true # Allow this job to fail without failing the pipeline


use_variable_job:
  stage: use_variable
  # needs:
  #   - set_variable_job
  # before_script:
  #   - source variable.env  # Load persisted variable

  script:
    - env
    - 'echo "Updated variable is: ${UPDATED}"' # Verify
  when: on_success  # Runs only if the previous stage succeeds


final_stage_job:
  stage: final_stage
  needs:
    - use_variable_job
  # before_script:
  #   - source variable.env  # Load persisted variable

  script:
    - env
    - 'echo "Updated variable is: ${UPDATED}"' # Verify
  
  rules:
    - when: always
