workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: always
    - when: never

stages:
  - set_variable  # Stage name
  - use_variable  # Stage name

set_variable_job: # Job name
  stage: set_variable # Correct stage association
  script:
    - VALUE=true
    - echo "EXPORT UPDATED=${VALUE}" > variable.env
    - 'echo "Updated variable is: ${VALUE}"'
  artifacts:
    paths:
      - variable.env

use_variable_job: # Job name
  stage: use_variable # Correct stage association
  needs:
    - set_variable_job
  script:
    - source variable.env
    - 'echo "Updated variable is: ${UPDATED}"'
  rules:
    - if: '${UPDATED} == "true"'