def GIT_BRANCH = ''
def envVars = [:]
def ENV_PREFIX = ''
def VERSION = ''
def current_infra_version = ''
def version_exists = ''
def TAG = ''
def aws_region = ''
pipeline {
    agent any
    tools {
        terraform 'Terraform 1.9.5 amd64'
    }

    environment {
        // Define environment variables
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        TF_API_TOKEN = credentials('TF_API_TOKEN')
        TF_SSH_PUBLIC_KEY = credentials('TF_SSH_PUBLIC_KEY')
    }

    stages {
        stage('Install AWS CLI') {
            steps {
                script {
                    sh '''
                        if ! command -v aws &> /dev/null; then
                            echo "AWS CLI not found. Installing..."
                            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                            unzip awscliv2.zip
                            sudo ./aws/install
                        else
                            echo "AWS CLI is already installed"
                        fi
                    '''
                }
            }
        }

        stage('Verify AWS CLI') {
            steps {
                sh 'aws --version'
            }
        }
    }
}