def GIT_BRANCH = ''
def envVars = [:]
def ENV_PREFIX = ''
def VERSION = ''
def current_infra_version = ''
def version_exists = ''
def TAG = ''
def aws_region = ''
pipeline {
    agent any
    tools {
        terraform 'Terraform 1.9.5 amd64'
    }

    environment {
        // Define environment variables
        //AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        //AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        TF_API_TOKEN = credentials('TF_API_TOKEN')
        TF_SSH_PUBLIC_KEY = credentials('TF_SSH_PUBLIC_KEY')
        AWS_CLI_PATH = "$HOME/.local/bin/aws"
    }

    stages {
        stage('AWS Demo') {
            steps {

                withCredentials([[ 
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'AWS_CREDENTIALS_ID',
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]){
                    sh 'aws s3 ls --region us-east-1'
                }

            }
        }
    }
}