version: '3.8'

services:
  jenkins:
    #image: jenkinsci/blueocean:latest #
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: on-failure
    ports:
      - "8080:8080"  # Exposes Jenkins on port 8080
      - "50000:50000"  # Port for Jenkins agent connections
      - "2376:2376" # used to add docker cloud nodes
    volumes:
      - jenkins_home:/var/jenkins_home  # Persistent volume for Jenkins data

volumes:
  jenkins_home:
    driver: local

