apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-depl
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: p1-docker-app
        image: p1-docker-app-local-2:1.2
        ports:
        - containerPort: 80
