apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-root-username: YWRtaW4=    # Base64 encoded "admin"
  mongodb-root-password: MTIzNA==    # Base64 encoded "1234"