- name: Example env var
  hosts: all
  become: yes

  environment:
    EXAMPLE: "Foo bar. tasks level"


  tasks:
    - name: Print Environment var at playbook level
      ansible.builtin.command: "echo $EXAMPLE"

    - name: Print env var at the task level
      environment: 
        MY_TASK_LEVEL_VAR: "Somehing task level"
      ansible.builtin.command: "echo $MY_TASK_LEVEL_VAR"
 
    - name: Print all the variables to find the task level one won't be printed
      ansible.builtin.command: "echo TASK_LEVEL_VAR: '$MY_TASK_LEVEL_VAR \n PLAYBOOK LEVEL ONE: $EXAMPLE'"
      #command also works
      register: output
  
    - name: print them
      debug:
        var: output['stdout']

    - name: Run with items greater than 5
      #ansible.builtin.command: echo {{ item }}
      debug:
        msg: "Item: {{ item }}"
      loop: [1,2,3,4,5,6,7,8,9,15]
      when: item > 5 

    - name: print ansible_facts
      debug:
        var: ansible_facts['distribution'] # ubuntu
      when: ansible_facts['os_family'] == "Debian"