name: Terraform CI/CD

on:
  push:
    branches:
      - dev
    paths:
      - 'app/terraform/**'  # Trigger only if Terraform files change
  # pull_request:
  #   branches:
  #     - master
  #   paths:
  #     - 'app/terraform/**'
permissions:
  actions: write  # Required to trigger workflows
  contents: read  # Required to checkout the repository

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}  # Authenticates with Terraform Cloud
      - name: Terraform Init & Validate
        run: |
          cd app/terraform
          terraform init
          terraform fmt -check
          terraform validate

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: validate
    environment: AWS
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}  # Authenticates with Terraform Cloud
      - name: Terraform Init & Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }} # Optionally add this
          TF_VAR_ssh_public_key: ${{ secrets.TF_SSH_PUBLIC_KEY }}
        run: |
          cd app/terraform
          terraform init
          terraform plan -out=tfplan          
      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: app/terraform/tfplan

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan
    environment: AWS
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}  # Authenticates with Terraform Cloud
      - name: Terraform Init  # 🔹 Ensure backend and workspace are initialized again
        run: |
          cd app/terraform
          terraform init
      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: app/terraform/
      - name: Terraform Apply
        run: |
          cd app/terraform
          terraform apply -auto-approve tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }} # Optionally add this
          TF_VAR_ssh_public_key: ${{ secrets.TF_SSH_PUBLIC_KEY }}
        if: github.event_name == 'push'

  trigger_deployer:
    name: Trigger Deployer
    runs-on: ubuntu-latest
    needs: apply
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Trigger src.yml Workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deployer.yml',  
              ref: 'master',  
            });
